variables:
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
  - export GEM_HOME="$HOME/.gem"
  - export PATH="/usr/local/opt/ruby/bin:$PATH"
  - export LDFLAGS="-L/usr/local/opt/ruby/lib"
  - export CPPFLAGS="-I/usr/local/opt/ruby/include"
  - export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"
  - export PATH="$HOME/.fastlane/bin:$PATH"
  - export MATCH_PASSWORD="$FASTLANE_MATCH_PASSWORD"
  - rbenv local 2.7.2

stages:
  - lint_generate_report
  - lint_check_report
  - build_project
  - tests
  
cache:
  paths:
    - public

pages:
  stage: lint_generate_report
  script:
    - make utils is_ci=true
    - make project is_ci=true
    - ./build-scripts/linter/ci/lint_generate_report.sh
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
          
  allow_failure: false
  artifacts:
    name: "$CI_PIPELINE_ID"
    paths:
      - public
    expire_in: 7 days
  tags:
    - mac-mini-ci
    
lint_check_report:
  stage: lint_check_report
  script:
    - ./build-scripts/linter/ci/lint_check_report.sh
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
  retry: 1
  allow_failure: false
  dependencies:
    - pages
  tags:
    - mac-mini-ci
    
build_project_debug:
  stage: build_project
  script:
    - make utils is_ci=true
    - make project is_ci=true
    - bundle exec fastlane ci_debug_build
  retry: 1
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

  allow_failure: false
  dependencies:
    - lint_check_report
  tags:
    - mac-mini-ci


build_project_release:
  stage: build_project
  script:
    - make utils is_ci=true
    - make project is_ci=true
    - bundle exec fastlane ci_release_build
  retry: 1
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

  allow_failure: false
  dependencies:
    - lint_check_report
  tags:
    - mac-mini-ci

unit_tests:
  stage: tests
  script:
    - make utils is_ci=true
    - make project is_ci=true
    - bundle exec fastlane unit_tests
  retry: 1
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

  allow_failure: false
  dependencies:
    - lint_check_report
  artifacts:
    when: always
    reports:
      junit: fastlane/test_output/UnitTests.xcresult/report.junit
  tags:
    - mac-mini-ci

ui_tests:
  stage: tests
  script:
    - make utils is_ci=true
    - make project is_ci=true
    - bundle exec fastlane ui_tests
  retry: 1
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

  allow_failure: true
  dependencies:
    - lint_check_report
  artifacts:
    when: always
    reports:
      junit: fastlane/test_output/UITests.xcresult/report.junit
  tags:
    - mac-mini-ci
