name: dota1x6

configs:
  Debug: debug
  Release: release

fileGroups:
    - README.md
    - Podfile
    - project.yml

configFiles:
  Debug: Config/Project-Debug.xcconfig
  Release: Config/Project-Release.xcconfig

options:
  defaultConfig: Debug
  groupSortPosition: top
  createIntermediateGroups: true
  useBaseInternationalization: true

include:
  - path: dota1x6/target.yml
