import "../build-scripts/fastlane/commonFastfile"

#---------------------------
# Uploading to App Center
#---------------------------

# Debug build
lane :beta do
  beta_common
end

# ---------------------------
# Update signings info.
# ---------------------------

# Get signing stuff only from Git.
lane :sync do |options|
  sync_common
end

# Get signing stuff from Git and update via Developer Portal.
lane :sync_force do |options|
  sync_force_common
end

# Get signing stuff from Git and update via Developer Portal. Create certificates if need.
lane :sync_force_certs do |options|
  sync_force_certs_common
end
