# Project Constants:

app_bundle_id: "com.baseapp"

# Какая схема приложения будет использоваться для создания Beta и Release сборок приложения.
scheme: "BaseApp"

# Имя приложения в appcenter
app_name: "BaseApp-iOS"

# AppleId под которым разрабатывается приложение. Необходимо для управления подписями и сертификатами.
apple_user: "audiofaun896373@gmail.com"

# Если один AppleID аккаунт состоит в нескольких командах, то необходимо указать id команды в котором идет разработка.
team_id: "Z4Q83QXW57"

# В какую ветку будет залита версия после команды fastlane beta
beta_branch: "beta"

# В какую ветку будет залита версия после команды fastlane release
release_branch: "appstore"

# В какую команду тестирования будут отправляться сборки для внутреннего тестирования.
appcenter_inner_group: "Collaborators"

# В какую команду тестирования будут отправляться сборки для тестирования заказчиком.
appcenter_customer_group: "BaseApp-public"

# Путь к файлу настройки проекта.
plist_path: "dota1x6/SupportingFiles/Info.plist"
